### PR TITLE
42 implement authentication

### PR DESCRIPTION
**Pull request by adzai**
- Added authentication and documentation. For documentation checkout http://localhost:8080/docs/index.html. It also describes the newly added endpoints. Libraries used: [sessions](https://github.com/gorilla/sessions), [securecookie](https://github.com/gorilla/securecookie).

- Removed --initialize parameter. Now the DB is checked every time the server is started, so the user table should get created when you first start the server.

- Added CORS headers. Be sure to create an environment variable ORIGIN_ALLOWED. The value of the variable for development can be *.

- Added PATCH to /user. The username or password can be changed if the user is authenticated.

- Added /logout endpoint.

- Restructured project layout.

### CODE REVIEW

**Review by Lucius1010011010 — APPROVED** [review]

**Review by AniSanikidze — APPROVED** [review]
Everything works well for me! Great work as always!

**Comment by Lucius1010011010** [comment]
Patch/user doesn't work. I ran it, then logged out and couldn't log in with the new password. The old one worked. The username got changed, but the password didn't.

Response body on the patch is
{
  "Status": 200,
  "Msg": "Successfully updated the username!"
  "User": null
}

**Comment by adzai** [comment]
> Patch/user doesn't work. I ran it, then logged out and couldn't log in with the new password. The old one worked. The username got changed, but the password didn't.

Works for me. You can only change 1 field at the time.

Change of username:

```json
{
    "newUsername": "newname"
}
```

Change of password: 

```json
{
    "oldPassword": "oldpass",
    "newPassword":"newpass"
}
```

**Review by Lucius1010011010 — APPROVED** [review]

**Comment by Lucius1010011010** [comment]
Yep, that explains that. Tried to do both at the same time.

**Pull request merged**
