### PR TITLE
22 updating of weekly menus, saved restaurants logic

### PR DESCRIPTION
**Pull request by adzai**
- Weekly menus now get updated every day at 11 AM
- Added `has-menu` parameter to restaurant queries
- Added `--download` flag that updates the restaurant schema and forces download of restaurants
- Added saved restaurants logic
- Added a distance field to restaurant JSON

You should use the `--download` flag when first starting so that your schema gets updated, since I added a new column there (all restaurants will get downloaded again). Alternatively you can alter the existing schema yourself if you want.

### CODE REVIEW

**Review by AniSanikidze — CHANGES_REQUESTED** [review]
The program saves the restaurant, the response status is 200, however, when I try to access the user information with GET request, the savedRestaurants field doesn't get updated, it is still null. The same happens when I log in.

**Comment by rifter42** [comment]
```
nextRun := time.Date(t.Year(), t.Month(), t.Day(), 11, 0, 0, 0, t.Location())
time.Sleep(time.Until(nextRun))
log.Println("Updating weekly menus...")
```

Honestly I don't like it. A process that's going to sleep for hours to then run once feels like a hack. What happens when we restart  backend, is update called every time after restart? I think we should use cron jobs instead. @adzai

**Comment by adzai** [comment]
> ```
> nextRun := time.Date(t.Year(), t.Month(), t.Day(), 11, 0, 0, 0, t.Location())
> time.Sleep(time.Until(nextRun))
> log.Println("Updating weekly menus...")
> ```
> 
> Honestly I don't like it. A process that's going to sleep for hours to then run once feels like a hack. What happens when we restart backend, is update called every time after restart? I think we should use cron jobs instead. @adzai

Of course it's a hack, as you can see in #47, I asked about this a month ago and nobody responded. If you want to rewrite this as a separate module that will be run as a cron job you can, because I'm not going to work on this anymore.

**Review by AniSanikidze — APPROVED** [review]
Everything works fine now!

**Comment by adzai** [comment]
> Everything works fine now!

Ok, since you merged everything from here I will close this in favor of #100.

**Pull request closed without merging**
