### PR TITLE
26 implement search

### PR DESCRIPTION
**Pull request by adzai**
Added `/restaurant/{id}` endpoint which returns a JSON for 1 restaurant based on provided ID.

The completion uses 2 built-in postgres extensions which you have to enable like so:

```sql
CREATE EXTENSION pg_trgm;
```
```sql
CREATE EXTENSION unaccent;
```
---

Implemented 2 new queries for `/restaurants` and `/prague-college/restaurants`

search-address=\<address\> Will take the provided address text and query the database for similar results.

search-name=\<name\> Will take the provided name text and query the database for similar results. 

The resulting JSON for both queries is ordered by similarity to provided text in a descending order.

---

Also added a new endpoint `/autocomplete` which can be queried for auto-completion suggestions in the search box. 
It supports completions for a restaurant's name and a restaurant's address.

Sample queries:

`/autocomplete?name=steak`

`/autocomplete?address=manesova`

The resulting JSON for both autocomplete queries is ordered by similarity to provided text in a descending order and has a max length of 10 completion candidates. The JSON looks like this:

```json
{
  "Status": 200,
  "Msg": "Success",
  "Data": [
    {
      "ID": 708,
      "Name": "Empír steak",
      "Address": "Beranových 39",
      "District": "Praha 9"
    },
    {
      "ID": 1061,
      "Name": "SteakBurger",
      "Address": "Krhanická 994/21a",
      "District": "Praha 4"
    }
  ]
}
```
The ID field can be used in case the user selects one of the suggestions to make a request to the backend for more info about only that specific restaurant.

I tested it a bit and the results seem pretty relevant, but it will be much easier to test it once it's integrated into the frontend.

### CODE REVIEW

**Review by AniSanikidze — APPROVED** [review]
Autocomplete works very well, great work! Regarding the number of suggested restaurants, I think  5-6 will be enough. Suggesting 10 restaurants will take the whole page and it won't look good in my opinion. But as I said during the meeting, I will work on 10 for now and will see how it turns out.

**Review by AniSanikidze — COMMENTED** [review]
@adzai  Also, I had an idea to display the pictures of suggested restaurants next to the name and address. Can you please add just one image for each restaurant in the JSON?

**Comment by adzai** [comment]
> @adzai Also, I had an idea to display the pictures of suggested restaurants next to the name and address. Can you please add just one image for each restaurant in the JSON?

Sounds good, I'll try to add it. But you'll have to handle the case where there isn't a photo provided. I'll have it as an empty string in that case.

**Comment by AniSanikidze** [comment]
> > @adzai Also, I had an idea to display the pictures of suggested restaurants next to the name and address. Can you please add just one image for each restaurant in the JSON?
> 
> Sounds good, I'll try to add it. But you'll have to handle the case where there isn't a photo provided. I'll have it as an empty string in that case.

No problem, I will replace it with the image placeholder that I used in the restaurant cards.

**Comment by adzai** [comment]
The JSON now contains an Image field with a URL string of an image or an empty string.

Also added a `/restaurant/{id}` endpoint which returns a JSON with only 1 restaurant based on the ID from autocomplete.
The structure is the same as the usual JSON, so it is still an array but it has only 1 element.

**Comment by AniSanikidze** [comment]
> The JSON now contains an Image field with a URL string of an image or an empty string.
> 
> Also added a `/restaurant/{id}` endpoint which returns a JSON with only 1 restaurant based on the ID from autocomplete.
> The structure is the same as the usual JSON, so it is still an array but it has only 1 element.

Nice! Everything works perfectly!

**Pull request merged**
