### PR TITLE
23 Fixed pagination, console errors, added scroll to top func 

### PR DESCRIPTION
**Pull request by AniSanikidze**
The problem of pagination not highlighting the correct current page was solved.  The scroll to top function was added whenever the filter or pagination is clicked. Besides this, there were some console errors while running the application, which is now solved, however, there still remains one warning :
image

From the researches I made, I figured out that this warning is solved in the newest version of React. I tried updating the react version to 17, but it caused conflicts with the version of the enzyme adapter module, which is used for unit tests. I have found an unofficial enzyme adapter with version 17, but react doesn't let me install it because of conflicts in the dependency tree.  I also tried updating the whole react app, but it didn't solve the problem either.

### CODE REVIEW

**Review by adzai — COMMENTED** [review]
Pagination works for me now, but I had a missing dependency chokidar, which I had to install with `npm i chokidar -f`

**Review by AgiliaErnis — APPROVED** [review]

**Comment by AniSanikidze** [comment]
> Pagination works for me now, but I had a missing dependency chokidar, which I had to install with `npm i chokidar -f`

That's strange because I tried deleting node modules and installing all the dependencies once again and still got no errors. 
Result of running the app :
image
Build:
image

But, anyway, I will still add chokidar dependency.

**Comment by adzai** [comment]
Still the same error

npm

**Comment by adzai** [comment]
It seems that the problem is with package-lock.json. I deleted package-lock.json and reinstalled with `npm install` and it works even without chokidar in package.json. Can you try to do the same e.g. remove chokidar from package.json, delete package-lock.json and redownload everything?

**Comment by AniSanikidze** [comment]
> It seems that the problem is with package-lock.json. I deleted package-lock.json and reinstalled with `npm install` and it works even without chokidar in package.json. Can you try to do the same e.g. remove chokidar from package.json, delete package-lock.json and redownload everything?

Yeah, the problem is that fsvents is not supported in your OS and yes, I will delete package-lock.json and reinstall everything.

**Review by adzai — APPROVED** [review]

**Review by Lucius1010011010 — APPROVED** [review]

**Pull request merged**
