### PR TITLE
43 user account design and integration with backend, frontend bug fixes

### PR DESCRIPTION
**Pull request by AniSanikidze**
Fixes:
- Removed the call to /autocomplete?name= when just going/refreshing the homepage
- Removed calls to /logo192.png
- Fixed filtration when one specific restaurant is searched and then all the restaurants are clicked.

Added:
- User logo and Menu in Navbar
- User account page with 4 sections: 
  - Saved restaurants
  - Change Password
  - Change Username
  - Delete Account.
- Added password strength meter for new passwords.
- Modals for phone numbers.
- Modals for weekly menus.

Problem: On page refresh, the user Menu in the navbar disappears. I tried storing log in state in local storage and getting the value from it and it works in console and in the Application tab. If you open the Application tab you will see the key – “user-logged-in” with the corresponding value. The value is correct and stays the same when refreshing the page, i.e, the user is still logged in, however, the user Menu gets replaced with login and sign up buttons. So, the state gets updated but the code doesn’t recognize it. I tried solving this problem in numerous ways but didn’t manage to find the problem.

### CODE REVIEW

**Comment by Lucius1010011010** [comment]
Failed to compile on my end.
./src/components/forms/signup/PasswordStrengthMeter.js
Module not found: Can't resolve 'zxcvbn' in 'C:\Users\mi\Documents\GitHub\restaurateur\frontend\src\components\forms\signup'
Not sure why, because I can clearly see the signup directory in the files.

**Comment by Lucius1010011010** [comment]
> Did you try `npm install` ?
Nope, and that explains that. Runs now. Danke.

**Review by adzai — COMMENTED** [review]
Some issues I found:

- When signing up, if my password is 6 characters long and I click sign up, nothing happens.
- Sometimes I have to click sign up twice to register, but that might be related to the issue above - e.g. I had password with 6 characters, something goes wrong and when I add more characters I have to click twice
- When I click on logout, it "logs me out" only on frontend. You have to make a call to `/logout` on backend as well.

**Comment by AniSanikidze** [comment]
> * When I click on logout, it "logs me out" only on frontend. You have to make a call to `/logout` on backend as well.

@adzai I integrated logout with backend and I can see in the console that it's working. I added console log for you to see the logout response. I don't know why the backend log doesn't show it.

**Comment by adzai** [comment]
> @adzai I integrated logout with backend and I can see in the console that it's working. I added console log for you to see the logout response. I don't know why the backend log doesn't show it.

You're right, I added logging to /logout on branch 22_updating_of_weekly_menus

**Review by adzai — APPROVED** [review]

**Comment by Lucius1010011010** [comment]
General wonkiness with Pale Moon probably due to the browser not being particularly good (user name doesn't display, cannot log out but no errors displayed etc.) Not something we can really fix, but something we can be aware of.

One problem with Brave I saw. When trying to delete user I got
`Failed to load resource: the server responded with a status of 400 (Bad Request)`
`:8080/auth/user:1`
two times, then kept getting
`DELETE http://localhost:8080/auth/user 400 (Bad Request)`
`useDeleteAccountForm.js:42`
on hitting the delete button. That's in the browser console.

Backend log is as follows:
2021/05/23 21:58:52 Incoming request
Method: "DELETE"
Client's address: "[::1]:56286"
Request URL: "/auth/user"
Handler: "userDeleteHandler"
Headers: map["Accept":["*/*"] "Accept-Encoding":["gzip, deflate, br"] "Accept-Language":["en-US,en;q=0.9"] "Connection":["keep-alive"] "Content-Length":["33"] "Content-Type":["application/json"] "Cookie":["session-id=MTYyMTc5OTkyOXwwQkdPR3RVUkprUS1rYlRpVFZ0emNYaklRQXN0NTVvdTA2dFhBSEFRaWVab3JzN2RvbE5faldoNWZjS1E0eHBEUnl1Z0tZSkQtQ2ltUy16WGIyQkZTVjJMeVBzSWRxVjRLalJCbkptZnlYamp0NWRvTVp6U0FDRXg3d0EwVVJLMk5PTTVUUGhnbEI0YTFDbmFhS1NGVk9GekhscUdsS1pSV1F1X3R3ZFZUUT09fDPwTOvEUQvOHGjQ-a2XfuSV63tMyUwvF8XutJrzqq0Y"] "Origin":["http://localhost:3000"] "Referer":["http://localhost:3000/"] "Sec-Fetch-Dest":["empty"] "Sec-Fetch-Mode":["cors"] "Sec-Fetch-Site":["same-site"] "Sec-Gpc":["1"] "User-Agent":["Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.212 Safari/537.36"]]

**Comment by adzai** [comment]
I was able to successfully delete the user but I got an infinite loop of calls to `/auth/user` when I entered the wrong password for the deletion of my account.

**Comment by Lucius1010011010** [comment]
Don't know what's going on, then. I am absolutely certain the password is correct - copy-pasted it in after logging in with the same, - and I'm not getting an 'incorrect password' warning. Does not delete the user, error is as mentioned above.

**Comment by Lucius1010011010** [comment]
Delete still broken on my end.
image

**Comment by AniSanikidze** [comment]
> I was able to successfully delete the user but I got an infinite loop of calls to `/auth/user` when I entered the wrong password for the deletion of my account.

@adzai The loop should be fixed now. @Lucius1010011010 Were you authorized when you did it? Maybe the cookies time was passed because error 400 is not about the incorrect password and you shouldn't get the incorrect password error.

**Comment by Lucius1010011010** [comment]
> Were you authorized when you did it?
> 
Define authorized.

**Comment by adzai** [comment]
>  @Lucius1010011010 Were you authorized when you did it? Maybe the cookies time was passed because error 400 is not about the incorrect password and you shouldn't get the incorrect password error.

I don't think that's it, unauthorized is 403. In the response JSON under Msg there should be a slightly more detailed response for the 400 reason. Try to console.log that

**Review by AgiliaErnis — APPROVED** [review]

**Pull request merged**
