### PR TITLE
13 deploy

### PR DESCRIPTION
**Pull request by rifter42**
Deployment to server

Needs secrets

### CODE REVIEW

**Comment by rifter42** [comment]
So this is about it, deploys our app to the server by buildings stuff inside containers. If you need node or go to be built differently let me know.

The workflow is now triggered on every published release, but if you want it to be triggered on only actual releases (without pre-releases), can be done too. 

Build is adapted to the app structure in the main branch btw.

**Comment by adzai** [comment]
> So this is about it, deploys our app to the server by buildings stuff inside containers. If you need node or go to be built differently let me know.

Go build in 0.2.0 is `cd cmd/backend && go build`

Node might need different build instructions as well, because if you go to https://restaurateur.tech/ there is an error `webpackHotDevClient.js:60 WebSocket connection to 'wss://restaurateur.tech/sockjs-node' failed` which suggests that it is running in development mode. 

Also there is a 500 on https://restaurateur.tech/restaurants - probably wrong URL address for the backend API. It suppose that the base URL should be configurable.

**Comment by rifter42** [comment]
> Go build in 0.2.0 is `cd cmd/backend && go build`

Added, but keep in mind that these changes aren't merged yet so it won't work when releasing main branch.

> Node might need different build instructions as well, because if you go to https://restaurateur.tech/ there is an error `webpackHotDevClient.js:60 WebSocket connection to 'wss://restaurateur.tech/sockjs-node' failed` which suggests that it is running in development mode.

I followed the instructions in our README, I gave up on understanding how to build node. It seems that you need to run `npm run` instead of `npm start` for production, but idk. @AniSanikidze if you know let me know pls.

> Also there is a 500 on https://restaurateur.tech/restaurants - probably wrong URL address for the backend API. It suppose that the base URL should be configurable.

Yea, because proxy settings we have rn don't work for Docker (localhost points only to the container itself). I changed it here https://github.com/AgiliaErnis/restaurateur/pull/102/commits/5b61881cb8dc414d4b38c842016692336fa77eb4, so it should work after we merge and release.

**Review by Lucius1010011010 — APPROVED** [review]
I don't know what Adam was saying about an error at the https://restaurateur.tech/restaurants page, everything runs for me.

**Comment by AgiliaErnis** [comment]
> I don't know what Adam was saying about an error at the https://restaurateur.tech/restaurants page, everything runs for me.

he means the console error
image

**Comment by AgiliaErnis** [comment]
Ignore CodeQL check, can't trigger it manually, I'm guessing it's because it's not on main, but on release-0.2.0

**Comment by adzai** [comment]
> he means the console error

No, she already resolved the issue with the 500.

**Review by adzai — APPROVED** [review]

**Comment by rifter42** [comment]
@AgiliaErnis can't merge without CodeQL check - can you merge manually?

**Comment by AniSanikidze** [comment]
> I followed the instructions in our README, I gave up on understanding how to build node. It seems that you need to run `npm run` instead of `npm start` for production, but idk. @AniSanikidze if you know let me know pls.

I think it's `npm run build` for production.

**Comment by AniSanikidze** [comment]
> I followed the instructions in our README, I gave up on understanding how to build node. It seems that you need to run `npm run` instead of `npm start` for production, but idk. @AniSanikidze if you know let me know pls.
 
I think it's `npm run build`

**Comment by AniSanikidze** [comment]
> > I followed the instructions in our README, I gave up on understanding how to build node. It seems that you need to run `npm run` instead of `npm start` for production, but idk. @AniSanikidze if you know let me know pls.
> 
> @rifter42  I think it's `npm run build`.

**Review by AniSanikidze — APPROVED** [review]

**Pull request merged**
