### PR TITLE
44 Search

### PR DESCRIPTION
**Pull request by AniSanikidze**
- Search engine suggests restaurants based on the user’s input. The maximum number of suggested restaurants is 10. The user can search restaurants by name or location.
- Each suggested restaurant is displayed with the corresponding Image, Name, Address, and District.
- Choosing the specific restaurant redirects the user to the Restaurants page and displays only that particular restaurant (later it can be connected to the View More, i.e., choosing a restaurant can automatically set View More to true and display all the information about that restaurant).
- The user can use the search engine by clicking on the search button, without choosing a particular restaurant.
- The search engine is included on the Restaurants page too. The suggested restaurants’ box can be closed by clicking on the section between Navbar and Footer.
- Clicking on Restaurateur Logo or Home page discards the chosen Restaurant.

Updates: 
- Added keyboard Navigation :
   - Arrow keys (Up/Down) scroll through the suggested restaurants.
   - If the cursor using arrow keys is not on the specific restaurant then the enter key works the same way as the search button. Otherwise, setting the cursor on the specific restaurant and then pressing enter displays only that restaurant.
   - Escape key hides the window of suggested restaurants.
   - Closing of the suggested restaurants window is now possible by clicking anywhere around the box.
   - The default input of searchbox is – “a”. So, clicking on the search input automatically gives suggestions for the input” a”. This input is hidden from the user. If the user types in searchbox, the default input will be replaced with the user’s input. 
- Disabled filtration when searching a certain restaurant.

### CODE REVIEW

**Comment by Lucius1010011010** [comment]
If you try to filter the search results, the app returns 'no restaurants found', even though some restaurants shouldn't be filtered out (e.g. price range of a restaurant is 0-300, but upon ticking that filter everything is filtered out).

**Comment by AniSanikidze** [comment]
> If you try to filter the search results, the app returns 'no restaurants found', even though some restaurants shouldn't be filtered out (e.g. price range of a restaurant is 0-300, but upon ticking that filter everything is filtered out).

Right, I forgot to test filtration. I will fix it.

**Review by Lucius1010011010 — APPROVED** [review]

**Comment by adzai** [comment]
This is very nice and looks very clean, good job! I have just 2 things to add:

1. I noticed that when you select 1 restaurant from autocomplete the filters stay ticked if you accessed the search box from the restaurants page. Wouldn't it be better to untick them or disable them when showing only 1 restaurant so that it's not misleading?
2. Would it be possible to implement some keyboard navigation for search? On most sites you can navigate the results with arrow keys or tab/shift-tab for example. Also, I expected that when I hit enter it will submit the search, but instead I had to click search with the mouse.

**Comment by AniSanikidze** [comment]
> This is very nice and looks very clean, good job! I have just 2 things to add:
> 
> 1. I noticed that when you select 1 restaurant from autocomplete the filters stay ticked if you accessed the search box from the restaurants page. Wouldn't it be better to untick them or disable them when showing only 1 restaurant so that it's not misleading?
> 2. Would it be possible to implement some keyboard navigation for search? On most sites you can navigate the results with arrow keys or tab/shift-tab for example. Also, I expected that when I hit enter it will submit the search, but instead I had to click search with the mouse.

Nice suggestions, will work on them.

**Comment by AniSanikidze** [comment]
Updates: 
- Added keyboard Navigation :
   - Arrow keys (Up/Down) scroll through the suggested restaurants.
   - If the cursor using arrow keys is not on the specific restaurant then the enter key works the same way as the search button. Otherwise, setting the cursor on the specific restaurant and then pressing enter displays only that restaurant.
   - Escape key hides the window of suggested restaurants.
   - Closing of the suggested restaurants window is now possible by clicking anywhere around the box.
   - The default input of searchbox is – “a”. So, clicking on the search input automatically gives suggestions for the input” a”. This input is hidden from the user. If the user types in searchbox, the default input will be replaced with the user’s input. 
- Disabled filtration when searching a certain restaurant.

**Review by adzai — APPROVED** [review]
The keyboard navigation works well for me, everything behaves as I would expect. I really like the idea of inputting "a" at the start. Maybe if we'll have time we could implement that when the user will be logged in, it could show suggested restaurants instead. 

All around great PR, good job!

**Pull request merged**
